sudo: required
language: node_js
node_js: "8"
services: docker

install: travis/install.sh

script: travis/test.sh

cache:
  directories: node_modules

deploy:
  provider: script
  script: travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master