sudo: required
language: node_js
node_js: "8"
services: docker

install: git clone https://github.com/Pajk/aws-beanstalk-docker-travis.git devops-ci

script: ./devops-ci/travis/nodejs/script.sh

cache:
  directories: node_modules

deploy:
  provider: script
  script: devops-ci/travis/beanstalk/script.sh
  skip_cleanup: true
  on:
    branch: master