FROM node:8-alpine

ENV HOME /home/node
ENV NODE_ENV production
ENV NPM_CONFIG_LOGLEVEL warn

# Tini init, see https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md
RUN apk add --update tini
ENTRYPOINT ["/sbin/tini", "--"]

WORKDIR $HOME

COPY . $HOME/

EXPOSE 3000

USER node

CMD ["node", "app.js"]
